### ISSUE TITLE
504 Gateway time-out 

### ISSUE THREAD

**Issue by annahurtta** [jquery/download.jqueryui.com#313]
I tried downloading a custom package and error 504 came with Chromium and Firefox.

**Comment by StevenLiekens** [comment]
Same problem here when trying to roll a new theme.

http://download.jqueryui.com/themeroller/parsetheme.css?ffDefault=Verdana%2CArial%2Csans-serif&fsDefault=1em&fwDefault=normal&cornerRadius=0&bgColorHeader=%2309C&bgTextureHeader=flat&borderColorHeader=%23000&fcHeader=%23FFF&iconColorHeader=%23000&bgColorContent=%23fff&bgTextureContent=flat&borderColorContent=%23000&fcContent=%23000&iconColorContent=%23000&bgColorDefault=%23DDD&bgTextureDefault=flat&borderColorDefault=%23000&fcDefault=%23000&iconColorDefault=%23000&bgColorHover=%23272727&bgTextureHover=flat&borderColorHover=%23000&fcHover=%23FFF&iconColorHover=%23FFF&bgColorActive=%23D4AA7D&bgTextureActive=flat&borderColorActive=%23000&fcActive=%23000&iconColorActive=%23000&bgColorHighlight=%23ffeb80&bgTextureHighlight=flat&borderColorHighlight=%23ffde2e&fcHighlight=%23363636&iconColorHighlight=%234ca300&bgColorError=%23cd0a0a&bgTextureError=flat&borderColorError=%239e0505&fcError=%23ffffff&iconColorError=%23ffcf29&bgColorOverlay=%23000&bgTextureOverlay=flat&bgImgOpacityOverlay=0&opacityOverlay=50&bgColorShadow=%23FFF&bgTextureShadow=flat&bgImgOpacityShadow=0&opacityShadow=0&thicknessShadow=0&offsetTopShadow=0&offsetLeftShadow=0&cornerRadiusShadow=0px&bgImgOpacityHeader=0&bgImgOpacityContent=0&bgImgOpacityDefault=0&bgImgOpacityHover=0&bgImgOpacityActive=0&bgImgOpacityHighlight=0&bgImgOpacityError=0

**Comment by opentechdiva** [comment]
Also getting Gateway error while trying to download stock theme....Any workaround to get the blaster theme?

**Comment by jzaefferer** [comment]
I just deployed 2 fixes. Can you try again? The "doesn't work" link above is now working.

**Comment by jzaefferer** [comment]
Also, if its not working for you, please keep this in mind:

> Please provide as much detail as you can about how you are customizing the theme. I cannot reproduce the error myself so I have to assume it's something specific to your requested build that is freaking the server out. Thanks!

**Comment by hh-com** [comment]
No, it doesnt work. (1.11.4, only Selectmenu)

**Comment by StevenLiekens** [comment]
I'll show you my custom theme. My particular problem is themeroller/parstheme.css. Sometimes it loads fast, sometimes it loads slow (1 minute TTFB), sometimes it times out (502).

http://download.jqueryui.com/themeroller/parsetheme.css?ffDefault=Arial%2CHelvetica%2Csans-serif&fsDefault=1em&fwDefault=normal&cornerRadius=3px&bgColorHeader=e9e9e9&bgTextureHeader=flat&borderColorHeader=dddddd&fcHeader=333333&iconColorHeader=444444&bgColorContent=ffffff&bgTextureContent=flat&borderColorContent=dddddd&fcContent=333333&iconColorContent=444444&bgColorDefault=f6f6f6&bgTextureDefault=flat&borderColorDefault=c5c5c5&fcDefault=454545&iconColorDefault=777777&bgColorHover=ededed&bgTextureHover=flat&borderColorHover=cccccc&fcHover=2b2b2b&iconColorHover=555555&bgColorActive=007fff&bgTextureActive=flat&borderColorActive=003eff&fcActive=ffffff&iconColorActive=ffffff&bgColorHighlight=fffa90&bgTextureHighlight=flat&borderColorHighlight=dad55e&fcHighlight=777620&iconColorHighlight=777620&bgColorError=fddfdf&bgTextureError=flat&borderColorError=f1a899&fcError=5f3f3f&iconColorError=cc0000&bgColorOverlay=aaaaaa&bgTextureOverlay=flat&bgImgOpacityOverlay=0&opacityOverlay=30&bgColorShadow=666666&bgTextureShadow=flat&bgImgOpacityShadow=0&opacityShadow=30&thicknessShadow=5px&offsetTopShadow=0px&offsetLeftShadow=0px&cornerRadiusShadow=8px

**Comment by annahurtta** [comment]
Doesn't work yet. Now i got error 524 A timeout occurred.
I tried downloading this:
http://jqueryui.com/download/#!version=1.12.0&components=111000100100110000000100011000001111111111111111

**Comment by jzaefferer** [comment]
Okay, thanks. Looks like there are a few more bugs inside one of the modules we're using. Please give us some time to address those. For now you can use this to download a bundle of all the themes: http://jqueryui.com/resources/download/jquery-ui-themes-1.12.0.zip

**Comment by michelc** [comment]
I try to download a custom 1.12 build with Draggable and Droppable only:
* I uncheck "Toggle All"
* I check "Draggable" and "Droppable"
* the URL is now : https://jqueryui.com/download/#!version=1.12.0&components=101000000100110000000000010000000000000000000000
* I don't need a theme, but the "Theme" area is empty
* I click the "Download" button

=> 504 Gateway time-out

I'm using Chrome Version "51.0.2704.106 m" on a french Windows 7 Professional SP1.

**Comment by druidoff** [comment]
The same problem
Error 504 Gateway time-out while trying to download autocomplete plugin on http://jqueryui.com/download/

**Comment by focusaurus** [comment]
Getting 504s trying to download a custom v1.12.0 package with just widgets: 

http://jqueryui.com/download/#!version=1.12.0&components=100000000000000000000000000000000000000000000000

Or all core: 

http://jqueryui.com/download/#!version=1.12.0&components=111111111111000000000000000000000000000000000000

**Comment by jzaefferer** [comment]
Thanks everyone, we have enough reports. Right now we need some patience, unless you want to help debugging the underlying issues. The software is all open source...

**Comment by vkeranov** [comment]
The empty "theme" is because of the same issue or not? I am also trying to download only "draggable" and "droppable"...

**Comment by jzaefferer** [comment]
Yes, that's part of the issue.

**Comment by jrlambs** [comment]
I'm having the same issue.  I go to http://jqueryui.com/  Select "Download" then scroll to the bottom and click "Download" button.  The request times out and I never get a download.  All options on the screen are left as default.

**Comment by Asimov500** [comment]
I am also having the same issue. I really need to download the new jquery ui. I have downloaded the full version temporarily but I like to customize it so i don't have such a big file. I am worried that if there are this many bugs in the page, I hate to see how many bugs are in the new jquery ui LOL.

**Comment by scottgonzalez** [comment]
# DO NOT POST ME TOO COMMENTS

**Comment by ucsdmath** [comment]
I realize your having time-out issues with your host (slow responses and times-out).
However, not all the time.  About 9 different tries and I was able to down load 1.12.0 (smooth) theme.  However, many times  I get "This site can’t be reached".  I tried with these:

  - Chrome Version 51.0.2704.106 (64-bit)
  - Safari Version 9.1.1 (10601.6.17)
  - Firefox 47.0.1

Keep up the good work!

**Comment by ucsdmath** [comment]
Sorry, the theme downloaded was a malformed zip file.  I was unable to get to the files.  There was no customizing of the smooth theme.  Anyway, all the best!

**Comment by Asimov500** [comment]
The themes and css are now downloading fine for me

**Comment by ucsdmath** [comment]
Very good work!  It seems to be working just fine now.  Thank you so much!

**Comment by thecheshirecat** [comment]
It's giving me the same error right now, error 504

**Comment by ThomasBaek** [comment]
Getting 504 aswell:
http://jqueryui.com/download/#!version=1.12.0&components=111111111111111111111111111111110000000000000000

**Comment by ryanbendel** [comment]
Getting a 504

1.12.0
Uncheck everything,
Add Draggable and Sortable,
This adds Widget, :data Selector, scrollParent, and Mouse

Link:
http://jqueryui.com/download/#!version=1.12.0&components=101000000100100010000000010000000000000000000000

**Comment by peveuve** [comment]
The problem still exists. Overall, the web site is very slow.

**Comment by NavinBro** [comment]
Hello,
Getting: Error 504

Link:
http://jqueryui.com/download/#!scope=css&version=1.12.0&components=101000010100110000000010010000001000100000000000&zThemeParams=5d000001001406000000000000003d8888d844329a8dfe02723de3e5701dc2cb2be0d98fe676bb46e85f3b85ff2d347a9c5170a6c17a4a3d926b08b9d199c4e573fcbf9cc1a2dd092a9d80b6fda5395ff84763f9e74d6cee21250c8f33243ef1589abab919cf7e8298f8769fec181781bf142e5e800e171d39cdf17e9a71fa3f781e8d76766b23c44b6d7f1e75c1abeef4410d820c31ef0620d79195b33d4cfc1e768094ce05fee304b2ad41db26904aed74c8c374ce1ff1c0a5c42f56dac08ad8961127638038b61b2703209b4091d7fb93a47a1d3e43a67c5a94b7e29c959f13c24559cb1a76b1bec1a71f1949db710f4557f3d1da2d39f90aff28f2b6ba8dd96ed5f5a0015166ef5567f70537d248d57b05c70e4fcc5845d9e1610b45d0d394c32ba0d5f992c00dca92aefe65863782767fcedea56a04e59e78457e74c5f1b23fdcd98c0b6bf4dbbe623d93fcb961477a3b6ff6f49245a0d75647ac7dcf1c860ed9882370de9a120924b3eaa4d72b858c41bd8bfbc944508a9fda3a42ff055dfa6e2ef96330dff48fe7a403db64306e0229493b498532edda2985338cbfd2dca06a59153f6300753623a533e25248b8dca8c2261083a9ebf73103a260168b2f957d138e17a4c80b5a901f1b748cff996db44f467265f09d1234456b9819fee221715dc98870f7e120db924d76acd66a3c270b2ee627140195c5c9e869d89c5acdf9330a84af5ae2c6c31792faa3aa55240bbecb844cb72dc1718194fff63506a7

**Comment by ryanbendel** [comment]
http://jqueryui.com/download/#!version=1.12.0&components=101000000100100010000000010000000000000000000000

Fails

**Comment by acolomitchi** [comment]
Error 504 Ray ID: 2c4dfc6bba8b1d68 • 2016-07-19 11:57:13 UTC 

On:
http://jqueryui.com/download/#!version=1.12.0&components=111111011111101000011101110100000000000000000000

(Toggle all, followed by selecting Dialog and Select Menu)

Sorry,  jzaefferer, from where I stand, 6 days does qualify for "some patience" already.

**Comment by scottgonzalez** [comment]
> At least a workaround suggestion would be highly appreciated.

Workaround: Grab the source files and do the concatenation and minification yourself.

**Comment by scottgonzalez** [comment]
I may have just fixed the problem.

## If you still have problems, please post a comment with the URL

If there are no errors reported over the next 24 hours, I'll close this as fixed.

**Comment by Asimov500** [comment]
I would be interested to know what the problem was and how it was fixed, as we are all developers here it might be a learning experience.

**Comment by scottgonzalez** [comment]
See the referenced commit above. I fixed a mixed content form submission for anyone accessing the site over HTTPS.

**Comment by dGilli** [comment]
I am still getting a 504 when trying to custom download:

http://jqueryui.com/download/#!version=1.12.0&components=000000000000000000000000000000001000000000000010

**Comment by ithav** [comment]
Hi there,
Still having 504 timeout error while trying to download custom 1.10.4.
after picking the modules & clicking "download" it takes about 2-3 minutes to get to the attached screen:
![504](https://cloud.githubusercontent.com/assets/9445082/17014916/e0c14b92-4f2f-11e6-8953-4f0ba1953fca.png)

Thanks in advanced.
ithav

**Comment by StevenLiekens** [comment]
> See the referenced commit above. I fixed a mixed content form submission for anyone accessing the site over HTTPS.

I get a similar timeout when I use plain HTTP. The status code is 524 instead of 504 and the cloudflare error is slightly different.

> The origin web server timed out responding to this request.

In case it helps trace the error, see this CloudFlare Ray ID: 2c5d152fb3a44457

**Comment by miczyz** [comment]
Error 504 Ray ID: 2c5d4827990d46c8 • 2016-07-21 08:30:23 UTC
Gateway time-out

**Comment by NavinBro** [comment]
Hello, I don't want to see all comment from githab on my mail. Can you make
something please?

21 июля 2016 г. 11:31 AM пользователь "miczyz" <notifications@github.com>
написал:

**Comment by scottgonzalez** [comment]
I had a feeling that wouldn't have fixed it, but at least downloads over HTTPS will work now.

@NavinBro Unsubscribe from notifications, please don't post on this issue to ask for help though.

# We're back to asking for no more me toos right now

**Comment by miczyz** [comment]
Great, works on http also.

**Comment by StevenLiekens** [comment]
It appears to work now. No more timeouts on my side.

**Comment by scottgonzalez** [comment]
And we're back to asking for reports of problems. We'll close in 24-48 hours if there are no more reports.

# Please post a comment if you have problems

**Comment by scottgonzalez** [comment]
Closing since there haven't been any more reports :-)

**Comment by jaimestuardo** [comment]
The problem is still present. Was jquery,ui abandoned? Error 502 appears. 

To reproduce it, just go to https://jqueryui.com/download/ and then click on Download at the bottom of the page.

Regards
Jaime

**Comment by dxsferrer** [comment]
Same here. For any combinations of widgets that I have tested so far I get the bad gateway error.

**Comment by EPurpl3** [comment]
Not working, error 502.
